version: '3'

volumes:
  dbdata:
    driver: local

networks:
  lib-net:

services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: '${database_user}'
      POSTGRES_PASSWORD: '${database_pass}'
      POSTGRES_DB: 'library_database'
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      lib-net:
        aliases:
          - database

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ancndz/library-java-base
    container_name: app
    restart: on-failure
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      database_user: '${database_user}'
      database_pass: '${database_pass}'
      database_host: '${database_host}'
    depends_on:
      - database
    ports:
      - '8088:8080'
    expose:
      - '8088'
    networks:
      lib-net:
        aliases:
          - app